In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as LA

In [ ]:
#Creating array in Python
z = np.array([1,2,3,4,5])
z

array([1, 2, 3, 4, 5])

In [ ]:
# Size
z.size

5

In [ ]:
# Accessing 4rd element
z[3]

4

In [ ]:
# Plotting vectors
x = np.array([2, 4])
y  = np.array ([3,5])
xchords, ychords = zip(x, y)
plt.scatter(xchords, ychords, color=["pink", "yellow"])
plt.axis([0, 9, 0, 8])
plt.show

In [ ]:
# 3D Vectors
a = np.array([1,4,6])
v = np.array([4, 6, 2])


In [ ]:
# Plotting 3D Vectors.
plotfor3d = plt.subplot(111, projection="3d")
xc, yc, zc = zip(a,v)
plotfor3d.scatter(xc, yc, zc)
plotfor3d.set_zlim3d([0, 9])
plt.grid()
plt.show()

In [ ]:
# Norm or Magnitude
distance = [-5, 7]
def norm_calculate(v):
  squares = [element **2 for element in v ]
  return sum(squares)**0.5

norm_calculate(distance)

8.602325267042627

In [ ]:
# Norm using numpy
import numpy.linalg as LA
LA.norm(distance)

8.602325267042627

In [ ]:
# Addition
t = a + v
t


array([ 5, 10,  8])

In [ ]:
# Multiplication by a scalar
g = a * 3
print(g)



[ 3 12 18]


In [ ]:
# Dot Product
a = np.array([1,5,7,9])
b = ([9,4,2,4])
c = np.dot(a, b)
c

79

In [ ]:
# Matrices in Python
M = np.array([[2,5,8], [5,9,2]])
M

array([[2, 5, 8],
       [5, 9, 2]])

In [ ]:
# Shape and size
M.size
M.shape

(2, 3)

In [ ]:
#element indexing
M[1,2]

2

In [ ]:
M[:,1]

array([5, 9])

In [ ]:
M[1,:]

array([5, 9, 2])

In [ ]:
M[1:2, :]

array([[5, 9, 2]])

In [ ]:
M[:, 2:3]

array([[8],
       [2]])

In [ ]:
# Sqaure, Diagonal, identity and Square Matrix
np.diag([4, 7,9])

array([[4, 0, 0],
       [0, 7, 0],
       [0, 0, 9]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Adding Matrices
A = np.array([[2, 5, 7,], [6, 7, 2]])
A

array([[2, 5, 7],
       [6, 7, 2]])

In [ ]:
B = np.array([[5, 3, 6], [6, 2, 2]])
B

array([[5, 3, 6],
       [6, 2, 2]])

In [ ]:
C = A + B
C

array([[ 7,  8, 13],
       [12,  9,  4]])

In [ ]:
# Sclar multiuplication with array
C * 2

array([[14, 16, 26],
       [24, 18,  8]])

In [ ]:
import numpy as np

C = np.array([[14, 16, 26],
              [24, 18, 8],
              [1, 2, 3]])  # Adjusted to 3x3 matrix

D = np.array([[2, 4, 6, 1],
              [8, 5, 3, 7],
              [0, 1, 2, 3]])  # Adjusted to 3x4 matrix

E = np.matmul(C, D)
print(E)


[[156 162 184 204]
 [192 194 214 174]
 [ 18  17  18  24]]


In [ ]:
# Matrix Transpose
A
A.T

array([[2, 6],
       [5, 7],
       [7, 2]])

In [ ]:
A.T.T

array([[2, 5, 7],
       [6, 7, 2]])

In [ ]:
K = np.array([[1, 3, 5], [2, 5, 7]])
L = np.array([[4, 5, 6], [7, 8, 9]])
(A+B).T

array([[ 7, 12],
       [ 8,  9],
       [13,  4]])

In [ ]:
#Converting 1D arrays to 2D array
U = np.array([2, 5])
u_row = np.array([U])
u_row


array([[2, 5]])

In [ ]:
U[np.newaxis, :]


array([[2],
       [5]])

array([[2],
       [5]])

In [ ]:
U[None]

array([[2],
       [5]])

In [ ]:
U[np.newaxis, :].T

In [ ]:
# Inverse
I = np.array([[4, 5], [2, 5]])
T = LA.inv(LA.inv(I))
T

array([[4., 5.],
       [2., 5.]])

In [ ]:
# Determinent
H = np.array([[3, 5, 7], [6, 7, 8,], [9,1,5]])
LA.det(H)


-107.99999999999993

In [ ]:
# Composing Linear Tranformation


In [ ]:
G, U, J = LA.svd(H)
G

array([[-0.49889159, -0.44465605, -0.74390065],
       [-0.69085039, -0.31423108,  0.65114098],
       [-0.52329048,  0.83877281, -0.15042357]])

In [ ]:
#Eigen Values and Eigen Vectors
eigenvec, eigenval = LA.eig(H)
eigenval

array([[-0.51181868, -0.65896916, -0.11060251],
       [-0.72153497, -0.18172326, -0.80080746],
       [-0.46629274,  0.72988787,  0.58862084]])

In [ ]:
eigenvec

array([16.42609064, -3.37449972,  1.94840908])

In [ ]:
#Trace
C = H.trace()
C

15